######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 16 00:33:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src/appContainer
INCLUDEPATH += .

# Input
SOURCES += src/appContainer/main.cpp
